### ISSUE TITLE
Allow some flags of public type to be private

### ISSUE THREAD

**Issue by strake** [bitflags/bitflags#143]
i.e

```rust
bitflags! {
    pub struct ABC: u8 {
        const A = 1;
        const B = 2;
        const C = 4;
        priv const D = 8;
    }
}
```

would become

```rust
pub struct ABC { bits: u8 }
impl ABC {
    pub const A: ABC = ABC { bits: 1 };
    pub const B: ABC = ABC { bits: 2 };
    pub const C: ABC = ABC { bits: 4 };
    const D: ABC = ABC { bits: 8 };
    fn all() -> Self { ABC { bits: 15 } }
    ...
}
```

I have a use case of a Unix file permissions type, where SUID, SGID, SVTX are public, but the RWX flags must be specified by combining with an enum representing user, group, other:

```rust
bitflags! {
    pub struct FileMode: u16 {
        const SUID = 0o4000;
        const SGID = 0o2000;
        const SVTX = 0o1000;
        priv const REST = 0o0777;
    }
}
```

Allowing `_` as a flag "name", to specify these flags are legal but unnamed, would also work in my case:

```rust
bitflags! {
    pub struct FileMode: u16 {
        const SUID = 0o4000;
        const SGID = 0o2000;
        const SVTX = 0o1000;
        const _ = 0o0777;
    }
}
```

**Comment by neachdainn** [comment]
I have also found myself wanting something like this.

My solution for the time being was do add a `#[doc(hidden)]` to the constant. It isn't as good of a solution as a private constant but it's better than a documented public one.

**Comment by KodrAus** [comment]
I think this is a case where defining your own semantic wrapper with just the constants you want to expose would be better. We'd potentially leak private constants in methods like `all` and when iterating over flags so I think it's best if we consider `bitflags` as always defining a public API to an underlying primitive bits container.
