### ISSUE TITLE
Allow other semantics of `PartialOrd`

### ISSUE THREAD

**Issue by strake** [bitflags/bitflags#155]
Now bitflags merely derives `PartialOrd` with the mechanism built into rustc, which compares the values numerically. But a flags type is also a Boolean lattice, so it has another natural partial order: `x ≤ y` iff `y.contains(x)`. As i can't disable deriving `PartialOrd` i can't use if the other semantics if wanted.

Either option would be fine:
• Let user disable deriving `PartialOrd` (and ergo `Ord`)
• Let user choose the semantics of `PartialOrd` per type

**Comment by bprosnitz** [comment]
I ran into this issue as well. IMO bitflags should use the natural partial order of the bits and this is a bug (though possibly difficult to change given existing usage)
