### ISSUE TITLE
Make `bits()` method const

### ISSUE THREAD

**Issue by raphaelcohn** [bitflags/bitflags#170]
Now that simple const functions are stable in Rust, it'd be useful to make the `bits()` method const. I've just added a wrapper around the `.bits` field to do this for a particular use case (assigned a bit-or of flags to another constant that needs to be of the underlying type) - but it'd be nice if the bitflags macro could do it.

**Comment by raphaelcohn** [comment]
@KodrAus - I'd probably slightly favour a `build.rs` approach and compiler version detection. It's a slight shame it's not possible to directly use the `#cfg` system for detecting the rust compiler version, or (for other problems, not this one) rely on a minimum version in Cargo.toml...

**Comment by kinggoesgaming** [comment]
> It's a slight shame it's not possible to directly use the #cfg system for detecting the rust compiler version, or (for other problems, not this one) rely on a minimum version in Cargo.toml


I believe a RFC is open that allows querying  for features

**Comment by kennethbgoodin** [comment]
I'd love to try this issue out. Looking over the Serde script now, but I would love any more input you have @KodrAus.

**Comment by KodrAus** [comment]
This is now supported in `1.0.5` when building on newer compilers.
