### ISSUE TITLE
1.0.5 seems to trigger a panic in rls rust language server, locking to 1.0.4 resolves it

### ISSUE THREAD

**Issue by anticrisis** [bitflags/bitflags#177]
Just thought you should be aware of this: https://github.com/rust-lang/rls/issues/1449

This panic causes editor integration in Visual Studio Code to break, among possibly other effects.

Workaround: Locking to 1.0.4 seems to resolve the problem for several people, myself included.

    [dependencies]
    bitflags = "=1.0.4"

**Comment by vadixidav** [comment]
[As was pointed out](https://github.com/rust-lang/rls/issues/1449#issuecomment-489348495), `1.0.5` can just be yanked to limit the impact and republished as `1.0.6` after it works with the RLS again.

**Comment by KodrAus** [comment]
We’ve yanked `1.0.5` for now so folks won’t have to pin a particular version of `bitflags`.
