### ISSUE TITLE
Misleading documentation on docs.rs

### ISSUE THREAD

**Issue by mystor** [bitflags/bitflags#178]
Despite to 1.0.5 being yanked in #177, the version currently documented at https://docs.rs/bitflags is 1.0.5. This misleadingly may lead a developer to believe that `bitflags` is `const fn` compatible, despite that not being released yet.

It may be a good idea to either yank the docs for 1.0.5 from https://docs.rs/bitflags, or perhaps release 1.0.6 which no longer triggers the RLS panic.

**Comment by KodrAus** [comment]
Hi @mystor :wave:

Thanks for the reminder! I meant to release a new version of `bitflags` after `1.35.0` hit stable, but it slipped my mind. I'm working on a release now that should clear up this confusion.
