### ISSUE TITLE
Empty bitflags definitions fail to parse

### ISSUE THREAD

**Issue by nox** [bitflags/bitflags#179]
This doesn't parse:

```rust
bitflags::bitflags! {
    pub struct BoxFlags: u8 {
    }
}
```

**Comment by KodrAus** [comment]
Hmm, it looks like we're using `+` rather than `*` as the repetition control. I can't imagine an empty set of `bitflags` would be very useful. Do you have a case where you've run into this?

**Comment by kinggoesgaming** [comment]
It might useful when introducing the type and designing the API first, before you even actually add the various bitflags

**Comment by KodrAus** [comment]
Yeh that seems fair. If there’s no reason to require bitflags have at least one item then we could probably just allow these to be written.

**Comment by nox** [comment]
> It might useful when introducing the type and designing the API first, before you even actually add the various bitflags

Yeah I was doing that, just propagating some flag value which I know I will need but didn't know yet what the flags themselves will be.

**Comment by Friz64** [comment]
You can just put something like this in there:
```rust
#[cfg(empty_bitflag_workaround)]
const EMPTY_BITFLAG_WORKAROUND = 0;
```
