### ISSUE TITLE
Typo in docs: "{Lower, Upper}Exp" should be "{Lower, Upper}Hex"

### ISSUE THREAD

**Issue by Shadlock0133** [bitflags/bitflags#182]
https://github.com/bitflags/bitflags/blob/fffdfe8379a745c88d6cbc17b4454789b499ee56/src/lib.rs#L131

**Comment by KodrAus** [comment]
Nicely spotted @Shadlock0133. Would you like to submit a PR to fix this?

**Comment by Shadlock0133** [comment]
Done in #183
