### ISSUE TITLE
`cargo build --test` fails on Windows

### ISSUE THREAD

**Issue by ecstatic-morse** [bitflags/bitflags#185]
[One of the tests](https://github.com/bitflags/bitflags/blob/8a10bdc144bb2a4b97c63cfa76be90228954d029/src/lib.rs#L920) for `bitflags-1.1.0` fails to compile on Windows with a stable rustc (version 1.36.0).

```
[INFO] [stderr] error[E0425]: cannot find value `_CFG_A` in this scope
[INFO] [stderr]    --> src\lib.rs:927:28
[INFO] [stderr]     |
[INFO] [stderr] 927 |             const _CFG_C = _CFG_A.bits | 0b10;
[INFO] [stderr]     |                            ^^^^^^ not found in this scope
[INFO] [stderr] 
[INFO] [stderr] error: aborting due to previous error
```

This suggests that `#[cfg]` attributes are not being properly added to `const` declarations, but I'm not quite sure exactly what's going on here.

**Comment by KodrAus** [comment]
Thanks for the report @ecstatic-morse! I'm not in front of my Windows box right now, but will look into this when I am, unless somebody else checks it first.

**Comment by ecstatic-morse** [comment]
I would guess that swapping `#[cfg(unix)]` and `#[cfg(windows)]` in that test will result in a failure on *nix. This arose while testing out `crater` runs on Windows.

**Comment by ecstatic-morse** [comment]
I'm guessing this test was a holdover from before `bitflags` used associated consts? Should be `Self::_CFG_A` right?

**Comment by KodrAus** [comment]
Thanks for looking into this @ecstatic-morse!

Yeh it looks like we didn't pick this up at the time because we aren't testing `bitflags` on Windows in CI. It would be nice to do this, but it would probably mean moving to something like Azure Pipelines, since AppVeyor is tricky to set up for an organization that doesn't have a single owner.
