### ISSUE TITLE
Support allow non_upper_case_globals lint.

### ISSUE THREAD

**Issue by crlf0710** [bitflags/bitflags#198]
I'm trying to create a bitflags with CamelCase naming. However adding #[allow(non_upper_case_globals)] everywhere doesn't suppress the lints.

**Comment by binarycrusader** [comment]
This is my only disappointment with bitflags; I know that technically the macro isn't generating an enum, but bit flags are frequently defined as enums in C/C++, and it's natural to prefer enum variant casing rules for the bitflags here.

**Comment by MagicRB** [comment]
When creating ffi bindings to c/c++ libs it gets especially annoying, having to have your bitflag variant name ANY_MODIFIER as opposed to AnyModifier to get rid of those warning is really annoying...

**Comment by hexagon-chunt-ricb** [comment]
@KodrAus How does #281 fix this issue? The `#[allow(non_upper_case_globals)]` lint still doesn't work anywhere, the only way to get it to work is to use `#![allow(non_upper_case_globals)]` for the entire file. Did I miss the solution?
