### ISSUE TITLE
matching on bitflags leads to unreachable patterns

### ISSUE THREAD

**Issue by gz** [bitflags/bitflags#201]
I was surprised to find out that matching on bitflags leads to unreachable patterns in the example below (i.e. `match_flag` always return 3). I'm assuming it conflicts with the `|` syntax in match arms, is this the intended behavior of bitflags?

```
use bitflags::bitflags;

bitflags! {
    pub struct Flag: u64 {
        const A      = 0;
        const B      = 1;
        const C      = 2;
    }
}

fn match_flag(f: Flag) -> usize {
    let a = Flag::A;
    let ab = Flag::A | Flag::B;
    let abc = Flag::A | Flag::B | Flag::C;
    match f {
        abc => 3,
        ab => 2,
        a => 1,
    }
}

fn main() {
    let abc = Flag::A | Flag::B | Flag::C;
    let ab = Flag::A | Flag::B;
    let a = Flag::A;
    
    assert_eq!(match_flag(abc), 3);
    assert_eq!(match_flag(ab), 2);
    assert_eq!(match_flag(a), 2);
}
```

**Comment by Alexhuszagh** [comment]
@gz I don't believe you know how Rust matches work.

Try the above, except with the following `match_flag` and you get the exact same issue:

```
fn match_flag(f: Flag) -> usize {
    match f {
        abc => 3,
        ab => 2,
        a => 1,
    }
}
```

What does that mean? It means the matches aren't actually considering the left-hand value, it's just used as a name for binding.

**Comment by Alexhuszagh** [comment]
@gz You can match the value of declared constants on the left-hand side, however, this is a bit tricky since bitflags does not override `|` as a a const fn.

What you can do however is:

```rust
fn match_flag(f: Flag) -> usize {
    const A: Flag = Flag::A;
    const AB: Flag = Flag::from_bits_truncate(Flag::A.bits() | Flag::B.bits());
    const ABC: Flag = Flag::from_bits_truncate(Flag::A.bits() | Flag::B.bits() | Flag::C.bits());
    match f {
        ABC => 3,
        AB => 2,
        A => 1,
        _ => 4,   // Needed for fallthrough
    }
}
```

**Comment by Alexhuszagh** [comment]
However, you will notice this **still** won't give you what you want, because `bitflags` and `0` work weirdly together: in short, `Flag::A` will match everything, because that's how 0 works: `Flag::A & flag == Flag::A` by default.

If you change your full example to:

```rust
extern crate bitflags; // 1.2.1

use bitflags::bitflags;

bitflags! {
    pub struct Flag: u64 {
        const A      = 1;
        const B      = 2;
        const C      = 4;
    }
}

fn match_flag(f: Flag) -> usize {
    const A: Flag = Flag::A;
    const AB: Flag = Flag::from_bits_truncate(Flag::A.bits() | Flag::B.bits());
    const ABC: Flag = Flag::from_bits_truncate(Flag::A.bits() | Flag::B.bits() | Flag::C.bits());
    match f {
        ABC => 3,
        AB => 2,
        A => 1,
        _ => 4,
    }
}

fn main() {
    let abc = Flag::A | Flag::B | Flag::C;
    let ab = Flag::A | Flag::B;
    let a = Flag::A;
    
    assert_eq!(match_flag(abc), 3);
    assert_eq!(match_flag(ab), 2);
    assert_eq!(match_flag(a), 1);
}
```

Then it will work.

**Comment by gz** [comment]
Yea sorry my example was broken in other ways because I reduced it by too much for the issue by accident. 

What I meant was exactly your last case where Flag::A matches everything because it has value 0. That seems like an odd pitfall when using bitflags with match.

**Comment by KodrAus** [comment]
That is a bit of a footgun, isn't it. In C# for instance, it's explicitly recommended to only define the `0` flags value to mean none. For `bitflags`, it sounds like we could improve our docs to suggest not defining a flag for `0`.

**Comment by KodrAus** [comment]
The crate docs already [had a section on the strange behavior of `0`](https://docs.rs/bitflags/1.3.2/bitflags/#zero-flags), but now include a final recommendation to avoid defining a `0` flag altogether.

I'll go ahead and close this one now, but if anything else comes up, please feel free to open more issues!
