### ISSUE TITLE
bitmaps with different endianess than the host

### ISSUE THREAD

**Issue by Trolldemorted** [bitflags/bitflags#209]
I'd like to use bitflags in an embedded environment (no_std, no allocator), where a certain memory region is mapped to a device.
Unfortunately it uses bitmaps whose byte order sometimes do not match the host's byte order. Could you make it possible to specify a field's byte order?

**Comment by KodrAus** [comment]
This is probably a bit too niche for `bitflags` itself to consider, but since you can add a `#[repr(transparent)]` to generated flags types to construct and re-interpret flags as their underlying integer this should be something that can be handled externally.
