### ISSUE TITLE
Entering doc strings via doc attribute fails

### ISSUE THREAD

**Issue by sameer** [bitflags/bitflags#214]
Consider the example below:
```rust
bitflags! {
  pub struct MyFlags: u8 {
    #[doc = "abc"]
    const FLAG = 0b1000_0000;
  }
}
```

This results in an error `no rules expected the token doc = "abc"`. [This style of docs is needed to use bitflags within another macro](https://github.com/sameer/bq24195/blob/master/src/lib.rs#L18) that gets docs from the caller.

**Comment by konsumlamm** [comment]
The example is working now for me, using the latest version.

**Comment by KodrAus** [comment]
Thanks for checking up on this @konsumlamm! I'll go ahead and close this one now.
