### ISSUE TITLE
Typo in documentation for `contains()`

### ISSUE THREAD

**Issue by camelid** [bitflags/bitflags#219]
**Current**:

https://github.com/bitflags/bitflags/blob/15e911c304d5bd8805af55d7e4f8c5324ed798ee/src/lib.rs#L680

**Fixed**:

```rust
/// Returns `true` if all of the flags in `other` are contained within `self`.
```

**Action**:

Add `if` between `` `true` `` and `all`

**Comment by jnqnfe** [comment]
Additional typos:

 1. "Use somthing else."

 2. Missing word "are" in "The Copy, Clone, PartialEq, Eq, PartialOrd, Ord and Hash traits automatically derived for the struct using the derive attribute." As in "[are] automatically derived".

**Comment by KodrAus** [comment]
Well spotted! If anybody would like to PR some doc/typo fixes that would be amazing 😁
