### ISSUE TITLE
Add example on conditionals

### ISSUE THREAD

**Issue by pickfire** [bitflags/bitflags#221]
It would be very common to check if flags are set, add examples to show how to use `intersects` and `contains`.

Without reading those, a reader might just try `if flags & Flags::A {` and to their surprise (beginners), it may not work.

So it would be nice to have an example to show how to do that, like `if flags.includes(Flags::A) {` and `if flags.contains(Flags::A | Flags::B)`.

**Comment by KodrAus** [comment]
Some examples and docs for these methods would be great! I'll end up doing a pass over the docs before we ship `2.0.0` but if anybody in the meantime would like to add some that would be most welcome.

**Comment by KodrAus** [comment]
In the last few years we've overhauled our documentation and introduced a much more organized test suite. I think together these changes should help new users get started with `bitflags`. If we wanted to make the library even more accessible, I think a section that introduces bitwise operations would probably be worth looking at.
