### ISSUE TITLE
const_bitflag_or macro to enable const bitflags before const traits are available

### ISSUE THREAD

**Issue by joshtriplett** [bitflags/bitflags#223]
Until const traits become usable on stable, it'd be nice to have a macro along the lines of `const_bitflag_or`, which would expand to use `Flags::NAME.bits()` and `Flags::from_bits_truncate`:

`const_bitflag_or!(Flags, A, B, C)`
would become
`Flags::from_bits_truncate(Flags::A.bits() | Flags::B.bits() | Flags::C.bits())`

**Comment by Evian-Zhang** [comment]
If we write `const_bitflags_or` as (since the delimiter can be anything):

```rust
macro_rules! const_bitflags_or {
    ( $Flags: ty, $( $flag: ident )|+ ) => {
        <$Flags>::from_bits_truncate(0 $(| <$Flags>::$flag.bits())+)
    };
}
```

Then we can use it like

```rust
const_bitflags_or!(Flags, A | B | C);
```

which may be more graceful.

**Comment by KodrAus** [comment]
Ideally we'll be able to just mark those traits as const when `#![feature(const_trait_impl)]` stabilizes. In the meantime, you can do:

```rust
Flags::A.union(Flags::B).union(Flags::C)
```

in const evaluation.

**Comment by KodrAus** [comment]
Just coming back through some triage. I think this isn't something we're going to support in `bitflags` through a macro, but will absolutely jump on `const_trait_impl` once it stabilizes. Thanks for the input everyone!
