### ISSUE TITLE
Build script results in SIGILL on old system.

### ISSUE THREAD

**Issue by MarioSieg** [bitflags/bitflags#226]
Hello,
I have a secondary very old PC to test my software on.

Specs (where it fails):
OS: Lubuntu x64
RAM: 2 GB DDR3
CPU: Pentium(R) Dual-Core  CPU E5500  @ 2.80GHz
HDD: 128GB
GPU: Integrated

I recently added the bitflags crate to my VM and the build script fails
with a "SIGILL Illegal Instruction" :(
To me this sounds like some SSE/AVX extension code was used, which is not supported on the
old CPU but I wasn't able to find the issue in build.rs.
It also only fails in release builds, debug builds work fine.
On my modern system everything is also working fine.

Modern Specs (where it works):
OS: Manjaro
RAM:  128GB DDR4 3600Mhz
CPU: AMD Ryzen Threadripper 3970x 32-Core
HDD: 10TB
SSD: 8TB
GPU: NVIDIA RTX 3090

Here is the terminal output on the old system:
![image](https://user-images.githubusercontent.com/49988901/95788020-ffdcdb00-0cda-11eb-96dc-9a56d95c7bd9.png)

Hope we will find a solution ^^

Best Regards,
Mario

**Comment by sollyucko** [comment]
It seems like the issue is somewhere in [the build script](https://github.com/bitflags/bitflags/blob/master/build.rs)? Does running just `cargo build` still trigger the error? What info do you get if you run `.../build-script-build` in a debugger?

**Comment by KodrAus** [comment]
As far as I know, Rust will expect avx and avx2 to be available by default. I'd be suspecting the `str::from_utf8` is the likely culprit.

I think fixing this would probably mean creating a [Cargo configuration file](https://doc.rust-lang.org/cargo/reference/config.html) and specifying target features or a target CPU that's compatible with your machine. There's some details on target feature and target CPU in [the portable SIMD docs](https://rust-lang.github.io/packed_simd/perf-guide/target-feature/rustflags.html).
