### ISSUE TITLE
Failing to compile on Apple M1

### ISSUE THREAD

**Issue by tuzz** [bitflags/bitflags#234]
Hello,

I'm trying to compile a project that uses bitflags on Apple Silicon. I'm currently getting:

```
Compiling bitflags v1.2.1 (/Users/tuzz/code/bitflags)
error: failed to run custom build command for `bitflags v1.2.1 (/Users/tuzz/code/bitflags)`

Caused by:
  process didn't exit successfully: `/Users/tuzz/code/bitflags/target/debug/build/bitflags-9675b0ecbbea8a2e/build-script-build` (signal: 9, SIGKILL: kill)
```

I'd like to try and help fix this if I can but I don't know where to start. I tried commenting out everything from the build script but it still failed. It did successfully compile `bitflags` when I removed the build script entirely.

Thanks

**Comment by KodrAus** [comment]
Hey @tuzz! :wave:

I think on M1 machines that SIGKILL actually comes from Apple's codesigning and usually indicates there's some x86-based bits somewhere in your toolchain. There are some more details here: https://github.com/rust-lang/rust/issues/79761
