### ISSUE TITLE
Allow `non_snake_case` on impl

### ISSUE THREAD

**Issue by saiintbrisson** [bitflags/bitflags#237]
I'm getting a warning about non-snake case function idents:
![image](https://user-images.githubusercontent.com/29989290/116169588-68b9fc80-a6db-11eb-9d02-e51a5359a788.png)

I noted that 
https://github.com/bitflags/bitflags/blob/c2ba43141307a97484518ad7728534855e1a51f2/src/lib.rs#L505-L507
and
https://github.com/bitflags/bitflags/blob/c2ba43141307a97484518ad7728534855e1a51f2/src/lib.rs#L594-L596
do not allow `non_snake_case` while their trait definitions do.

Should rust-analyzer be suppressing this warning, or could we allow `non_snake_case` on the impls?

**Comment by SaiintBrisson** [comment]
I've suggested suppressing the warning on rust-analyzer https://github.com/rust-analyzer/rust-analyzer/issues/8675.

**Comment by KodrAus** [comment]
We could also freely pepper `#[allow()]`s in more places where we generate those warnings ourselves.
