### ISSUE TITLE
Considerations for 2.0

### ISSUE THREAD

**Issue by KodrAus** [bitflags/bitflags#262]
Before we actually release a build with #220 I think it’s a good time to consider any breaking changes that could work their way into a `2.0` release. Without much public surface area I think the risk of multiple `bitflags` versions in a dependency graph is low.

Some I had in mind:

- Reconsider making `from_bits_unchecked` unsafe. The idea was to make it unsafe to construct flags using bits that don’t correspond to flags specified. That way an implementor could consider using things like `unreachable_unchecked` in code that matches on bits. In hindsight this just seems like something people work around rather than make use of. Since we generate types in the scope of the `bitflags!` invocation there’s already nothing stopping someone from manually stuffing extra bits in a flags type. So we can’t rely on `from_bits_unchecked` in `bitflags` code either.
- Consider not deriving any traits by default. Ship an optional proc macro `#[bitflags_derive]` that can be used to add them. That way callers can decide on their own equality and debug implementations if they want.
- Consider changing the serialization implementation to use a text format for human-readable formats and raw bits for others.
- Anything else?

**Comment by KodrAus** [comment]
I've started sketching out an alternative implementation for a `2.x` in #264. It allows us to add `#[derive]` support for external libraries like `arbitrary` without potentially breaking callers, but comes with some potential breakage:

```diff
bitflags! {
+   #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
    struct Flags: u32 {
        const A = 0b00000001;
        const B = 0b00000010;
        const C = 0b00000100;
-       const ABC = Flags::A.bits | Flags::B.bits | Flags::C.bits;
+       const ABC = Flags::A.bits() | Flags::B.bits() | Flags::C.bits();
    }
}
```

If you want to derive `Serialize`, then you'd add a `serde` feature to `bitflags`, then add it. This is different from today, but would be consistent with any other traits we support, like `Arbitrary`.

This gives you a chance to change the way you implement traits like `Debug` and `PartialOrd` in the same way you would for any other type, but does require a stack of `#[derive]`s to be equivalent to `1.x` types.

How do people feel about this? I don't want to create churn that doesn't seem worthwhile, but if it's palatable then it gives us a way to naturally tweak trait implementations. There's a middle-ground here where you would include `#[derive]`s for some of these types, like `Clone`, `Copy`, and `Hash`, and exclude others that may want alternative implementations like comparison.

What do you all think?

**Comment by Rua** [comment]
For my own use case, making it safe to include unknown bits in the flags could actually introduce UB. It relies on not receiving any unrecognised bits, because it needs to check the validity of each bit before passing it on to a foreign API (Vulkan). Unrecognised bits could potentially violate the API if left, and if the user could introduce an unchecked bit *safely*, then that could lead to UB in safe code, which goes against what Rust tries to do.

Having no guarantee that the bitflags values received by functions are all valid in safe code, would mean that every Rust function has to run every bitflags type it receives through `from_bits_truncate` to ensure validity. But that would also remove the ability by the user to include unrecognised bits that *are* ok to use, if the user knows what they are doing, which is the whole point of `unsafe`.

**Comment by roblabla** [comment]
Maybe an attribute could be given like `#[allow_unknown_bits]` or something.

**Comment by GilShoshan94** [comment]
> > I'd love to have a well-documented way to construct bitflags in a constant. Right now, I use a macro
> 
> That’s probably the most ergonomic looking way until `impl const` lands. There are some nice const methods if you don’t mind chaining:
> 
> ```
> TheBitflagsType::Flag1.union(TheBitflagsType::Flag2).union(…)
> ```
> 
> A general lack of nice examples is another issue 🙂

Hi, I am pretty new to Rust and could not find if what I am about to propose is possible.
While a lot of methods are cons such as `union` and `intersection` and we can chain them, it is nicer and more readable to use operators.

```Rust
const SPECIFIC_FLAG: TheBitflagsType = TheBitflagsType::Flag1 | TheBitflagsType::Flag2).union | … ;
```
Is nicer and more intuitive than:
```Rust
const SPECIFIC_FLAG: TheBitflagsType = TheBitflagsType::Flag1.union(TheBitflagsType::Flag2).union(…);
```

So my question and suggestion is:
Could the operators be `const` function ?
I looked into the code and for the Bitwise OR `|` operator, it seems that currently the code is (line 726 in lib.rs):
```Rust
impl $crate::_core::ops::BitOr for $BitFlags {
            type Output = Self;

            /// Returns the union of the two sets of flags.
            #[inline]
            fn bitor(self, other: $BitFlags) -> Self {
                Self { bits: self.bits | other.bits }
            }
        }
```
Could changing 
```Rust
fn bitor(self, other: $BitFlags) -> Self {
```
 to 
```Rust
const fn bitor(self, other: $BitFlags) -> Self {
``` 
work  and make it useable in constant ?
Same for the other operators (!, &, ^).

**Comment by roblabla** [comment]
> So my question and suggestion is:
Could the operators be const function ?

It is currently impossible to use traits from const functions, including the operator trait, in stable rust. The operators on integers/floats/etc... are special cased to work in const context.

So, no, unfortunately, that is not currently possible.

**Comment by GilShoshan94** [comment]
@roblabla 
Thank you for the explanation, I didn't know.
Hope it will come in stable Rust.

**Comment by KodrAus** [comment]
> For my own use case, making it safe to include unknown bits in the flags could actually introduce UB.

@Rua is there a repository somewhere with your use-case I could take a look at?

**Comment by djdisodo** [comment]
can you allow to add attribute for field `bits`

**Comment by KodrAus** [comment]
Hi @djdisodo :wave: Could you elaborate a bit on what you mean? Which attributes would you like to add to the `bits` field?

**Comment by djdisodo** [comment]
@KodrAus any attribute, just like current bitflags macro handles attributes that will be applied to expanded struct
($outer)

i'm planning to use [helper attribute](https://doc.rust-lang.org/reference/procedural-macros.html#derive-macro-helper-attributes) to the field

**Comment by KodrAus** [comment]
@djdisodo Hmm, the plan for `2.0` at this stage is to change the type of that field to make it anonymous so that we have some control over how that field implements other traits. You probably won't be able to meaningfully add arbitrary attributes to it. If there's a library with a trait that you want to implement then we can consider adding a feature flag for it.

**Comment by coderedart** [comment]
just here to express support for serializing to text in human readable formats like json.

**Comment by reitermarkus** [comment]
Somewhat related to 

> Reconsider making from_bits_unchecked unsafe. 

I'd like to have something like

```rust
fn bits_mut(&mut self) -> &mut u16;
```

Currently I am using an enum to switch between `&mut u16` and `&mut MyBitFlags`.

**Comment by KodrAus** [comment]
Hey all! :wave:

Things have been moving slowly but surely here, and now have #282 that splits responsibilities between the user-facing API and the `bitflags` internal API. This means users are responsible for exposing more on their generated flags types, but in `bitflags` we can make `#[derive]`s on ecosystem traits possible to opt-in to.

In `1.x` you'd write:

```rust
bitflags! {
    pub struct Flags: u32 {
        const A = 0b00000001;
        const B = 0b00000010;
        const C = 0b00000100;
        const ABC = Flags::A.bits | Flags::B.bits | Flags::C.bits;
    }
}
```

In `2.x` you'd write:

```rust
bitflags! {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct Flags: u32 {
        const A = 0b00000001;
        const B = 0b00000010;
        const C = 0b00000100;
        const ABC = Flags::A.bits() | Flags::B.bits() | Flags::C.bits();
    }
}
```

to get an equivalent flags type. You can still generate flags without the `#[derive]` block just fine:


```rust
bitflags! {
    pub struct Flags: u32 {
        const A = 0b00000001;
        const B = 0b00000010;
        const C = 0b00000100;
        const ABC = Flags::A.bits() | Flags::B.bits() | Flags::C.bits();
    }
}
```

and you'll get some set-operators, but none of the traits you'd normally derive, just as if you were writing a plain-old-struct. If you didn't want your flags type to derive `PartialOrd`, you simply don't add it to your `#[derive]`, and can implement it manually instead if you'd like.

This new approach gives us more flexibility, but it comes at a cost: you have to do more work when generating flags types. I'm conscious of how easy it can be to trade ergonomics for flexibility to the point that nobody finds upgrading worthwhile. So I'd love to hear from anyone out there with flags types they'd now need to start peppering `#[derive]`s all over whether or not that effort seems worthwhile for them.

**Comment by CasperN** [comment]
I don't think adding derive statements are that annoying but if its an issue, you could introduce a second macro, e.g. `bitflags_extended!`, for power users, and keep `bitflags!` for providing ergonomic defaults.

**Comment by KodrAus** [comment]
I've merged #282 which does most of the internal refactoring to let us separate the API `bitflags` owns from the API end-users own. Along with that I've changed `unsafe fn from_bits_unchecked` to `fn from_bits_retain`. It's functionally the same, but no longer unsafe.

The last thing we need to do before being able to put out a pre-release is make the iterators we generate for enabled flags a concrete type instead of `impl Iterator`.

**Comment by KodrAus** [comment]
I've just published a `2.0.0-rc.1` version of `bitflags` that includes the following changes:

- There's a `BitFlags` trait that makes it possible to work with flags types generically.
- You can iterate over set flags and their names, as well as get a flag value from its name. These should support cases where you want to serialize/deserialize flags as strings.
- You now need to add more `#[derive]`s so you get better control over the semantics of formatting and equality.
- We now have a private type to add manual trait implementations like `Arbitrary` to that users can then opt-in to through `#[derive]`s.

I think this is an exciting release and am keen for any feedback on how you all find it!

**Comment by coderedart** [comment]
> You can iterate over set flags and their names, as well as get a flag value from its name. These should support cases where you want to serialize/deserialize flags as strings.

does that mean serializing to json or other text formats will just serialize the number representing bits rather than text names?

**Comment by reitermarkus** [comment]
> The unsafe `from_bits_unchecked` method is now a safe `from_bits_retain` method.

Given this is safe now, would it make sense to call this `from_bits` and call what is now `from_bits` `from_bits_lossy` instead?

**Comment by KodrAus** [comment]
@coderedart If you previously derived `serde` traits then adding a `#[serde(transparent)]` attribute will guarantee your flags will serialize exactly the same as they did before (which is the bits as an integer).

We don’t have a parser for the `Flag1 | Flag2` format used in formatting yet, but do now generate the boilerplate to parse the stringified names of individual flags to their values for you. So we could write a fully generic parser based on the `BitFlags` trait that let you serialize using a textual representation of your flags instead of the integer.

**Comment by KodrAus** [comment]
Since we do already require the `#[serde(transparent)]` attribute on existing flags types I think we could consider using a text representation for human-readable flags by default and let you use `#[serde(with)]` to maintain the old behavior.

**Comment by coderedart** [comment]
instead of `Flag1 | Flat2` etc.., isn't it simpler to just separate them by a comma? `Flag1,Flag2`. 

or even a sequence `["Flag1", "Flag2"]`. anything of these is fine as a default, and as you already said, people can use the `#[serde(with)]` attribute for their custom use cases. 

As this is a breaking semver anyway, its the best time to adopt such a change (or explicitly reject it).

**Comment by KodrAus** [comment]
It would be easier to use a sequence for sure. I think a reason to have a canonical string format is that it would open up support for opting in to `FromStr`, `Display`, etc and target the lowest common datatype that you’d expect a format or schema to support.

**Comment by KodrAus** [comment]
In #297 I've started work on a text parser for flags formatted using bar-separated-names, like:

```
A | B | 0x8f
```

That PR also updates our default `serde` implementation to use formatted strings for human-readable formats and the underlying integer type directly for binary formats. There were a few things I wanted to call out and get some input on:

- Are we comfortable changing the default serialization format in this bump? It's a major version change so I think if there's any time to do it it would be then, but may break already serialized data.
- If you format `Flags::empty()` with a default derived `Debug` impl, you'll get `Flags(0x0)`. The `0x0` is a placeholder for an empty set of flags, because we parse hex numbers, so `0x0` will be naturally parsed as empty. The alternative is to simply produce an empty string, but I felt like it might be surprising for a format to not write any output at all. We could split `Debug` and `Display` here, since the `Display` impl on an empty string is itself an empty string so there's precedent there. Do you have any preferences on one approach or another?

**Comment by coderedart** [comment]
1. I prefer not changing the default. making it opt-in would ensure easier transition for existing crates. and users like me who need readable flags, will manually opt into this change. Although, we should mention in README and top level docs that this option exists, so that new users can use this instead of wasting time writing their own serialization functions. 
2. I think empty string makes sense. if there's no flags set, then there's no data to be serialized.

**Comment by KodrAus** [comment]
Missing the fact that your serialization defaults will change when you bump the library version is definitely a concern for me.

My own opinion is that we should change the default while we have some reasonable chance to do so, call it out explicitly in the release notes along with a demonstration of how to keep the existing behavior if you rely on it. We’re moving from an unconsidered default of serializing to a struct with an integer field to a considered (and I think entirely superior)  one of serializing to a formatted string for end-users or the underlying bits directly for compact formats. #298 is an example of where the current default is simply unsuitable for compact users and #147 is an example for end-users.

**Comment by nim65s** [comment]
Hi,

As a new user, I can say I was really puzzled when my embedded systems stop working when I added some bitflags in my messages. It didn't took long to find that the deserialization was raising errors, and then it didn't took long to find that only the messages with bitflags were raising errors, and then it didn't took long to workaround conversions from and to `u8`s, but overall it was not the best experience.

So obviously I'm biased, but even if I understand that changing the default is not an easy decision to take, I'd be in favor of doing it 😅

**Comment by KodrAus** [comment]
I've opened #299 to push a new RC release that includes the change to the default serialization format. It will now use a formatted string for human-readable formats and the underlying bits
type for compact formats.

To keep the old behavior, see the [`bitflags-serde-legacy`](https://github.com/KodrAus/bitflags-serde-legacy) library.

**Comment by KodrAus** [comment]
If everything looks good, I'll leave this release candidate around for a few weeks and publish it as a stable `2.0.0` with no other changes on March 1st 🙂

**Comment by KodrAus** [comment]
`2.0.0` should be up on crates.io shortly, so I think we can finally call this issue closed :tada: Thanks to everyone who contributed their input to this release, I hope this foundation will help the library best serve its users for a long time to come.
