### ISSUE TITLE
A case for `impl From<Hashset<&str>>`

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [bitflags/bitflags#283]
When serializing bit flags they quickly become unreadable and not easily editable.

This can be somewhat awkwardly circumvented by using something like:
```rust
bitflags! {
    struct Flags: u32 {
        const A = 0b00000001;
        const B = 0b00000010;
        const C = 0b00000100;
        const ABC = Self::A.bits | Self::B.bits | Self::C.bits;
    }
}
pub fn serialize<S>(date: &Flags, serializer: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    let mut base = format!("{:032b}", date.bits());
    let mut offset = 0;
    for i in (4..32).step_by(4) {
        base.insert(i + offset, $crate::bitflags_util::NIBBLE_SEPARATOR);
        offset += 1;
    }
    base.serialize(serializer)
}
```
outputting something like:
```
"flags": "1111_1110_1101_1000_0011_0010_0000_0011"
```
This is better but still lacking.

If all bit flags derived `TryFrom<HashSet<&str>>` and `TryInto<HashSet<&str>>` this would allow behavior like:
```rust
assert!(Flags::try_from(["A", "B"].into_iter().collect::<HashSet<_>>()).is_ok());
// It would be worth considering here if we fail when a flag not specified is activated by another.
// Perhaps best to return `Result<Self,Self>` such that we inform a user, but they can still decide to proceed.
assert!(Flags::try_from(["A", "B", "ABC"].into_iter().collect::<HashSet<_>>()).is_err());
assert!(Flags::try_from(["A", "B", "C", "ABC"].into_iter().collect::<HashSet<_>>()).is_ok());

assert_eq!(HashSet::try_from(Flags { bits:  3}), ["A", "B"].into_iter().collect::<HashSet<_>>())
assert_eq!(HashSet::try_from(Flags { bits:  7}), ["A", "B", "C", "ABC"].into_iter().collect::<HashSet<_>>())

let _= serde_json::to_string(HashSet::try_from(Flags { bits:  3}).unwrap()).unwrap();
// Saved like `"flags": ["A", "B"]`
let _= serde_json::to_string(HashSet::try_from(Flags { bits:  7}).unwrap()).unwrap();
// Saved like `"flags": ["A", "B", "C", "ABC"]`

```

**Comment by KodrAus** [comment]
Thanks for the suggestion @JonathanWoollett-Light! We now support something like this by supporting [creating flags types from names](https://docs.rs/bitflags/latest/bitflags/trait.BitFlags.html#tymethod.from_name), and you an also [opt-in to `FromStr` for parsing flags from strings](https://github.com/bitflags/bitflags/blob/main/examples/fmt.rs#L31-L37). For the specific case of serialization, the default format for human-readable formats like JSON through `serde` is now strings like `A | B | C`.

I don't think we need to implement `From<HashSet<&str>>` specifically, but have made some definite improvements in working with flags represented as strings.
