### ISSUE TITLE
Generate tests on bitflags

### ISSUE THREAD

**Issue by laralove143** [bitflags/bitflags#284]
I'm not sure if this is possible with macros, but it'd be a nice addition to increase coverage, I have no experience with macros so I probably can't PR this sadly

**Comment by KodrAus** [comment]
Anything that improves our test coverage would be greatly appreciated! It has improved a lot over time, but even without experience writing macros something that would be very helpful is calling out where coverage is bad so we can improve it in specific places 🙂

**Comment by KodrAus** [comment]
Just coming back through some triage. I don't think there's anything actionable for this right now so I'll go ahead and close this one.

Thanks again for the input!
