### ISSUE TITLE
Unclear documentation for `from_bits_unchecked`

### ISSUE THREAD

**Issue by nicholasbishop** [bitflags/bitflags#292]
The documentation for [`from_bits_unchecked`](https://docs.rs/bitflags/latest/bitflags/example_generated/struct.Flags.html#method.from_bits_unchecked) says in part:

> The caller of the bitflags! macro can chose to allow or disallow extra bits for their bitflags type.

It's unclear to me if this means there's some way to call `bitflags!` that allows/disallows extra bits, or if this just means that the caller is supposed to indicate in the docstring if "unknown" bits are allowed so the caller of `from_bits_unchecked` knows if it's safe to pass unknown bits.

**Comment by edgarogh** [comment]
I'm wondering the same thing. From `bitflags`s point-of-view, is it UB to call `from_bits_unchecked` with a random number, or is the crate owning the struct free to do whatever it likes?

**Comment by KodrAus** [comment]
We made the `from_bits_unchecked` method unsafe originally because I had some vague reservations about keeping "invalid" bit patterns out of flags. It turns out that doesn't really win us anything, so as of `2.0.0-rc.1` this method has been refactored into a safe `from_bits_retain` method.

**Comment by KodrAus** [comment]
One of the issues with `from_bits_unchecked` was that you could safely `#[derive(Serialize)]` for instance, and then safely deserialize some random integer as your flags type and suddenly have an invalid flag. It was misguided to make it unsafe 🙂

**Comment by KodrAus** [comment]
This is sorted in `2.0.0` now, where the `from_bits_retain` method has clear semantics.
