### ISSUE TITLE
Should the `BitFlags` trait subtrait `BitAnd` et al.?

### ISSUE THREAD

**Issue by PatchMixolydic** [bitflags/bitflags#293]
I'm currently using `bitflags` to implement collision bitmasks in a game engine. Of course, since different games use collision for different things, I decided to try making my collider type generic over the mask type using the `BitFlags` trait. However, this didn't quite work:

```
error[E0369]: no implementation for `M & M`
   --> triplicata/src/collision.rs:222:53
    |
222 | what_collided: self.accept_mask & other.generate_mask,
    |                ---------------- ^ ------------------- M
    |                |
    |                M
    |
help: consider further restricting this bound
    |
157 | impl<M: BitFlags + std::ops::BitAnd<Output = M>> Hitbox<M> {
    |                  ++++++++++++++++++++++++++++++
```

Since the types created by `bitflags!` always implement `BitAnd` ([alongside several other traits](https://docs.rs/bitflags/2.0.0-rc.1/bitflags/index.html#whats-implemented-by-bitflags)), it might be convenient for `BitFlags` to subtrait `BitAnd` et al. Is this feasible?

(I realize I could probably just use `BitAnd` as a bound on its own in this case, but I'd like to push users towards using `bitflags` to define their bitmasks.)

cc #262

**Comment by KodrAus** [comment]
Hi @PatchMixolydic :wave:

I think the only reason we don't currently use `Bit*` traits as supertraits was to keep the initial scope of `BitFlags` small since the trait itself is quite new. We may allow the trait to be implemented manually at some point, in which case we'd have to be careful about what additional traits we've inherited from the `bitflags!` macro. To be fair, the `Bit*` traits are probably not contentious as supertraits of `BitFlags`.

In the meantime, you can use the `intersection` method as an alternative to `&`.

**Comment by rusty-snake** [comment]
To leave a more complex example:

```rust
fn contains_uncorresponding_bits<T, U>(flags: T) -> bool
where
    T: BitFlags<Bits = U> + BitAnd<Output = T>,
    U: Not<Output = U>,
{
    !(flags & (T::from_bits_retain(!T::all().bits()))).is_empty()
}
```

> In the meantime, you can use the intersection method as an alternative to &.

The `BitFlags` trait does not have "Set" methods (`intersection`, `union`, `difference`, ...).

**Comment by rusty-snake** [comment]
Ok, this should give you almost everything:
```rust
use core::fmt::{Binary, LowerHex, Octal, UpperHex};
use core::ops::{
    BitAnd, BitAndAssign, BitOr, BitOrAssign, BitXor, BitXorAssign, Not, Shl, ShlAssign, Shr,
    ShrAssign, Sub, SubAssign,
};
trait BitFlagsExt {
    fn complement_retain(self) -> Self;
    fn has_uncorresponding_bits(self) -> bool;
}
impl<T, U> BitFlagsExt for T
where
    T: BitFlags<Bits = U>
        + BitAnd<Output = T>
        + BitAndAssign
        + BitOr<Output = T>
        + BitOrAssign
        + BitXor<Output = T>
        + BitXorAssign
        + Not<Output = T>
        + Sub<Output = T>
        + SubAssign
        + Extend<T>
        + FromIterator<T>
        + IntoIterator
        + Binary
        + LowerHex
        + Octal
        + UpperHex,
    U: BitAnd<Output = U>
        + BitAndAssign
        + BitOr<Output = U>
        + BitOrAssign
        + BitXor<Output = U>
        + BitXorAssign
        + Not<Output = U>
        + Shl<Output = U>
        + ShlAssign
        + Shr<Output = U>
        + ShrAssign
        + Add<Output = U>
        + AddAssign
        + Div<Output = U>
        + DivAssign
        + Mul<Output = U>
        + MulAssign
        + Neg
        + Rem<Output = U>
        + RemAssign
        + Sub<Output = U>
        + SubAssign,
{
    fn complement_retain(self) -> Self {
        Self::from_bits_retain(!self.bits())
    }

    fn has_uncorresponding_bits(self) -> bool {
        !(self & Self::all().complement_retain()).is_empty()
    }
}
```

**Comment by KodrAus** [comment]
> The BitFlags trait does not have "Set" methods (intersection, union, difference, ...).

Ah, those are methods I think we should add to the `Bits` trait.

**Comment by KodrAus** [comment]
In #348 I made the `BitFlags` trait far more useful and publicly implementable. I don't think we'll add all these supertrait bounds directly so that the trait is easy to implement, but have added the set operator methods to it that are automatically implemented for you.

Thanks for the input everyone!
