### ISSUE TITLE
feat: Add minimum permissions to your workflows

### ISSUE THREAD

**Issue by gabibguti** [bitflags/bitflags#304]
Adding minimum permissions to GitHub workflows is important to protect your repository against supply-chain attacks. GitHub, by default, gives higher permissions to workflows but [recommends adjusting them to minimum permissions as necessary](https://docs.github.com/en/actions/security-guides/automatic-token-authentication). I see `rust.yml` seems to be used for tests, and the tests don't need much permissions. `contents: read` permission would be enough to perform the `actions/checkout` and `actions-rs/cargo`. If you'd like I can open a PR to make the changes!

Also, this is considered good-practice and recommended by security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

##### Additional Context
I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by KodrAus** [comment]
Hi @gabibguti :wave:

If you’d like to submit a PR that tightens these up that would be awesome!
