### ISSUE TITLE
Add a method to retrieve numerical value of muti-bit flags

### ISSUE THREAD

**Issue by jotare** [bitflags/bitflags#318]
Hi! I recently started using this crate in a side project and I really miss function to obtain the numerical value from a concrete flag.

My use case is a byte which contains flags of multiple bits, like:
```rust
bitflags! {
    struct Flags: u8 {
        const MY_FLAG = 0b0011_0000;
        ...
    }
}
```

In this case, I'd like to match on the flag value (from 0 to 3) without having to shift the value and have to know exactly how many bits I have to shift, i.e., avoiding this pattern:
```rust
match myflags.intersection(Flags::MY_FLAG) >> 4 {
    ...
}
```
As it breaks the encapsulation `bitflags` offers.

I would love some function like `from_bits_truncate` in the inverse way, something like:
```rust
myflags.into_bits_intersect(Flags::MY_FLAG)
```

I can contribute if you want.

Thanks in advance :)

**Comment by KodrAus** [comment]
Hi @jotare! :wave:

This seems like it might be a bit of a niche case without fully understanding what you're working on. I think you can shift your flags values without breaking encapsulation though using `trailing_zeros`:

```rust
Flags::MY_FLAG.bits() >> Flags::MY_FLAG.bits().trailing_zeros()
```

Would that suit your needs?

**Comment by jotare** [comment]
Hi, thanks for the fast reply!

I'm working on an emulator for the NES Picture Processing Unit and it has some flags encoded within multiple bits. For example, they join two bits to get a numeric value instead of a boolean. The particular case is really specific but I thought a group of bits coding an integer instead of a single bit coding a bool wasn't that rare.

Even though, I find your solution pretty neat and solves my issue. So, thank you!

**Comment by KodrAus** [comment]
Just coming back through some triage. I think we can call this one resolved, but if you have any future feedback or suggestions please feel free to open new issues for them!
