### ISSUE TITLE
`usize` / `isize` aren't supported anymore in `v2.0`

### ISSUE THREAD

**Issue by CryZe** [bitflags/bitflags#319]
This doesn't seem intentional at least and isn't mentioned in the changelog.

**Comment by sollyucko** [comment]
In what way are they not supported? What error message do they give? Or is there some other problem with them?

**Comment by CryZe** [comment]
They don't implement the new `Bit` trait, which is required to use bitflags: https://github.com/bitflags/bitflags/blob/main/src/traits.rs#L135-L141

**Comment by KodrAus** [comment]
Thanks for pointing this out @CryZe. This is a total oversight, they should implement the `Bits` trait.
