### ISSUE TITLE
Regression in v2: flag constants no longer appear in `cargo doc` output

### ISSUE THREAD

**Issue by nicholasbishop** [bitflags/bitflags#320]
Steps to reproduce:
```
cargo new --lib bitflags-missing-docs
cd bitflags-missing-docs
cargo add bitflags
```

Replace `src/lib.rs` with:
```rust
bitflags::bitflags! {
    pub struct Flags: u32 {
        /// Hello.
        const HELLO = 1;
    }
}
```

Run `cargo doc --open` and search for "hello". It doesn't find anything of that name, and if you go to the `Flags` page it indeed has no documented constants.

![image](https://user-images.githubusercontent.com/1023208/226126074-30b4abeb-0fcf-41a6-8eef-9bce0857993f.png)

If you change `Cargo.toml` to use `bitflags = "1"` and re-run `cargo doc`, the constant is there as expected:

![image](https://user-images.githubusercontent.com/1023208/226126123-7e9076d3-5551-40d6-ac64-05db76a4de37.png)

**Comment by nicholasbishop** [comment]
I think this is due to https://github.com/bitflags/bitflags/pull/282, as demonstrated with this example:

```rust
pub struct A;
pub struct B;

impl A {
    pub const VAL: u32 = 0;
}

const _: () = {
    impl B {
        pub const VAL: u32 = 0;
    }
};

pub const B2: u32 = B::VAL;
```

Running `cargo doc` on that shows `A::VAL` but not `B::VAL`.

**Comment by KodrAus** [comment]
This issue is fixed upstream, but won't make it to a stable release until April 20th so it might be worth us mitigating it here anyways. It should be fairly straightforward. We can split the `impl` block that defines those constants from the one that implements other methods and move the constants to outside the `const _: () { .. }` block.

**Comment by nicholasbishop** [comment]
Thanks for the fix :)
