### ISSUE TITLE
feat: Add Security Policy

### ISSUE THREAD

**Issue by gabibguti** [bitflags/bitflags#335]
Adding a Security Policy is important to provide guidance on how users can report potential vulnerabilities and also raise awareness of when vulnerabilities will be confirmed, fixed and disclosed.

I recently recommended https://github.com/bitflags/bitflags/issues/304 and, like that change, this one also considered a good-practice and recommended by [Github](https://docs.github.com/en/code-security/getting-started/securing-your-repository#setting-a-security-policy) and [Scorecard](https://github.com/ossf/scorecard).

If you agree, I can open a PR to suggest a Security Policy, and we can work together to communicate how the repo can best handle vulnerability reports.

##### Additional Context
Hi again! I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by KodrAus** [comment]
Hi @gabibguti :wave: We should be able to use GitHub's own _Security_ feature to handle collection and communication of reports, right? If there's some standard policy we could adopt here I'd be very keen to do so :+1:

**Comment by gabibguti** [comment]
@KodrAus Hi! Yeah, sure!

In GitHub's Security tab, you can create / display a Security Policy and also create / handle reports through Security Advisories [report vulnerability](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability) feature.

If you'd like to take a look, the example below shows what I usually suggest following GitHub's suggested policy structure and reporting through Security Advisories:
https://github.com/Cyan4973/xxHash/security/policy
