### ISSUE TITLE
Methods on generated flags types not being detected as const

### ISSUE THREAD

**Issue by KodrAus** [bitflags/bitflags#337]
I am getting this (cut for brevity):

![image](https://user-images.githubusercontent.com/6416159/230246418-50e1255c-d3c1-475d-9e8c-ac8b499ca9da.png)

The very strange thing is that docs.rs does indeed show those as const.  But my local build of the docs shows them as not const:

![image](https://user-images.githubusercontent.com/6416159/230246644-d95bf267-2b8c-473e-b06f-c3dcaf101efe.png)

EDIT: I should have been more clear: docs.rs shows these fns as const in the bitflags 2.0.x docs.  Building my own docs for my crate locally shows that they are not const with 2.x.  But the docs for my crate on docs.rs are const using bitflags 1.3.x, and that is what is triggering semver-checks to fail.

_Originally posted by @molpopgen in https://github.com/bitflags/bitflags/issues/310#issuecomment-1498352871_

**Comment by KodrAus** [comment]
@molpopgen Did you ever get to the bottom of this? Would it be possible to share your version of `rustc` you're using to build with?

**Comment by molpopgen** [comment]
No, I haven't solved it. I put off an upgrade until there's another reason to bump the minor version. (The crate in question is pre-1.0 still).

```
❯ rustc --version
rustc 1.68.2 (9eb3afe9e 2023-03-27)
```

**Comment by KodrAus** [comment]
Hmm, this looks like it could be a `rustdoc` bug that was fixed at some point? If I upgrade `tskit` to `bitflags` 2 and build the docs with `rustc 1.70.0-nightly` I see the methods appear as `const`:

<img width="1220" alt="Screenshot 2023-04-12 at 5 54 17 pm" src="https://user-images.githubusercontent.com/6721458/231391478-c6d50478-5119-410f-bd64-793e5370de24.png">

If I rebuild using `1.68.2` I don't see them as `const`:

<img width="1237" alt="Screenshot 2023-04-12 at 5 58 02 pm" src="https://user-images.githubusercontent.com/6721458/231391597-321ef29f-b467-4d5f-b514-f0c77f136dde.png">

They do appear to be `const` though. If I add a `const fn` that uses them, methods like `intersects` still work.

**Comment by molpopgen** [comment]
Very interesting.  I'll try to confirm this myself later today.  The possibility of `rustdoc` bugs is definitely a weakness for using `semver-checks` in one's CI :(.

**Comment by molpopgen** [comment]
I confirmed this on my end -- now only the removal of `from_bits_unchecked` gets flagged.  I think we can close this one.

**Comment by KodrAus** [comment]
Thanks @molpopgen!

Yeh, it seems like there have been a few issues specifically around consts that have been getting ironed out with `rustdoc` lately. It looks like they're pretty swiftly resolved though.

I'll go ahead and close this one, but please do open fresh issues for anything else you encounter!
