### ISSUE TITLE
Allow opting-out of `InternalBitFlags` `fmt`/`FromStr` impls?

### ISSUE THREAD

**Issue by daniel5151** [bitflags/bitflags#347]
Would it be possible to add an "opt-out" feature to the `bitflags!` macro that disables generating the `core::fmt` and/or `FromStr` impls on `InternalBitFlags`?

Obviously not final syntax, but I was thinking something along the lines of:

```rust
bitflags::bitflags! {
    !impl FromStr;
    !impl fmt;

    #[derive(Copy, Clone)]
    pub struct Flags: u32 {
        const A = 1;
        const B = 2;
        const C = 4;
        const D = 8;
    }
}
```

Thinking more broadly: it might be interesting to consider extending this idea to arbitrary subsets of the generated API (or even having having a complimentary `bitflags_with!` macro where you manually _opt-in_ to various impls), but I thought I'd start by asking about the most pressing use-case first.

* * *

For context, I'm using `bitflags!` in a library designed to run in very resource constrained environments, where every single byte of code matters.

While updating to `bitflags` version 2, I noticed a (relatively) substantial binary size bump in my test binaries, and after digging into it, I narrowed things down to a "spooky action at a distance" interaction between the code in the generated `FromStr` impl, and some unrelated code elsewhere in the project. You can read the details over at https://github.com/daniel5151/gdbstub/pull/138#issuecomment-1529128170, but suffice it to say, I was quite surprised to see that seemingly "dead code" could still affect codegen like that.

Of course, this is something I can (and will) work-around on my end, but thought I might as well open the issue anyways.

* * *

I should note that this might not be as niche of an ask as you might think.

Many embedded Rust projects avoid `core::fmt` and `core::str` methods/machinery like the plague, as they can result in substantial binary bloat on resource constrained platforms. The popularity of projects like [`ufmt`](https://github.com/japaric/ufmt) and [`defmt`](https://github.com/knurling-rs/defmt) are due in no small part to the inefficiencies of the core lib in embedded contexts.

Given that `bitflags` is commonly used in these sorts of projects, it would be nice to have a opt-in way to squeeze every last ounce of performance from the generated code (without resorting to hand-rolling a custom `bitflags` macro).

**Comment by KodrAus** [comment]
Hi @daniel5151! :wave:

In general, I'd like to avoid any additional configuration in the macros to keep the scope of the project contained. We could consider some Cargo features to opt-out of various trait impls on `InternalBitFlags`, but that would only solve the problem of your `check_size.sh` script reporting an increase though, because once `bitflags` appears in a dependency tree with those impls enabled it'll increase again.

It seems like in this case it's not really a `bitflags` issue, and trying to solve it at the `bitflags`-level may be a game of whack-a-mole, where any newly added code could trigger the bloat.

Something we could do that would also help #339 is offer a macro like `bitflags` that simply generates public methods on your own custom flags type:

```rust
pub struct MyFlags(u32);

bitflags_lite! {
    MyFlags: u32
}
```

**Comment by daniel5151** [comment]
Yep, I think the wack-a-mole analogy is super appropriate here. Projects like mine have to be very careful when taking on dependencies, since you never know when a seemingly innocuous update causes an unexpected binary size bump (case-in-point).

In any case - if this functionality isn't something you're interested in adding, I totally understand. It's admittedly a pretty niche ask, and I agree that most folks won't care/notice the extra compile time hit of emitting those unused traits/methods (only to have the compiler strip them out).

For what it's worth, I would absolutely _love_ to have something like `bitflags_lite`.

Of course, your concerns around communication are perfectly valid, and getting the right naming/docs around that sort of feature would be super important. Maybe something like `bitflags_base` would be better? Not sure...

Anyhoo, in the short-term, I'll just re-jig my own code to avoid that call to `.trim()`, since it shouldn't have been there to begin with (https://github.com/daniel5151/gdbstub/commit/6e00943d9f06826a112b96aa8be7a9819809869f). The alternative would be to switch away from `bitflags`, and honestly, this crate is just too dang good at what it does to consider doing that 😅

**Comment by KodrAus** [comment]
I've been working on a general solution to the problem of more deeply customizing your flags type without losing the code generation. Here's what I've come up with: https://github.com/bitflags/bitflags/issues/348#issuecomment-1535532991

@daniel5151 You might find this a useful way to more tightly control what code is pulled in when generating your flags types 🙂

**Comment by daniel5151** [comment]
Oh, nice! That `impl ManualFlags` macro would be perfect for my use-case :)

And sorry for the delayed response!

**Comment by KodrAus** [comment]
Just coming back through some triage. I think the `impl Flags` variant of `bitflags!` is the solution we have for this kind of problem so I'll go ahead and close this one.

Please feel free to open new issues with any other suggestions or problems you encounter!
