### ISSUE TITLE
Clippy warnings around "manual implementation of an assign operation"

### ISSUE THREAD

**Issue by sciguyryan** [bitflags/bitflags#357]
Hi.

I've run into a new clippy lint warnings such as the following:

> manual implementation of an assign operation
> for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assign_op_pattern
> `#[warn(clippy::assign_op_pattern)]` on by default

I'm following the example from the docs page for the use of the macro (more or less, as below). Can you enlighten me as to why this lint notification is appearing here and if there is some way to fix it? I know I can silence the warnings, it's just annoying to see it pop up whenever I run into it.

```rust
bitflags! {
    pub struct MemoryAccess: u8 {
        /// None.
        const N = 1 << 0;
        /// Public read.
        const R = 1 << 1;
        /// Public write.
        const W = 1 << 2;
        /// Private read.
        const PR = 1 << 3;
        /// Private write.
        const PW = 1 << 4;
        /// Execute.
        const EX = 1 << 5;
    }
}
```

Thanks!

**Comment by sciguyryan** [comment]
Believe it or not I did search first, that didn't come up. Seems like I was searching for the wrong thing there.

Diolch.

**Comment by KodrAus** [comment]
We have some rather ad-hoc treatment of lints and warnings that `bitflags`'s own code may generate. I've (finally) added a `clippy` step to our CI so we should stop triggering lints in your code so regularly 😅
