### ISSUE TITLE
Problems deriving serde after upgrading

### ISSUE THREAD

**Issue by BearOve** [bitflags/bitflags#360]
I'm trying to derive serde after upgrading to bitflags 2. I have created a bare-bones example repository that shows the issue.

Repo: https://github.com/BearOve/repro-bitflags-serde-2023.05.19
Rust versions: 1.69.0 and nightly from 2023-05-19
Error:
```
error[E0277]: the trait bound `InternalBitFlags: Deserialize<'_>` is not satisfied
  --> src/main.rs:3:1
   |
3  | / bitflags::bitflags!(
4  | |     #[derive(Deserialize, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
5  | |     #[serde(transparent)]
6  | |     pub struct Test: i32 {
...  |
11 | |     }
12 | | );
   | |_^ the trait `Deserialize<'_>` is not implemented for `InternalBitFlags`
   |
   = help: the following other types implement trait `Deserialize<'de>`:
             &'a Path
             &'a [u8]
             &'a str
             ()
             (T0, T1)
             (T0, T1, T2)
             (T0, T1, T2, T3)
             (T0, T1, T2, T3, T4)
           and 125 others
   = note: this error originates in the macro `__declare_public_bitflags` which comes from the expansion of the macro `bitflags::bitflags` (in Nightly builds, run with -Z macro-backtrace for more info)
```

This looks like a bug to me, as I'm not doing anything special or complicated and it used to work before.

**Comment by KodrAus** [comment]
Hi @BearOve 👋 

You just need to enable the `serde` feature of `bitflags` and you’ll be able to derive `serde` traits. We should probably call this out better in the README now.

Do note though that the default serialization format is different in `bitflags` 2, it will use a string for human-readable formats like JSON. You can retain the old behaviour. There are details in [the release notes for `2.0.0`](https://github.com/bitflags/bitflags/releases/tag/2.0.0)

**Comment by BearOve** [comment]
Thanks, will give that a go
