### ISSUE TITLE
Inconsistent debug output for flag with no bits

### ISSUE THREAD

**Issue by sunfishcode** [bitflags/bitflags#364]
In a bitflags type where one of the named value has the value 0, the debug output for the type sometimes includes that value by name, and sometimes doesn't, apparently depending on whether any unrecognized bits are present. For example, this:
```rust
use bitflags::bitflags;

bitflags! {
    #[derive(Debug)]
    pub struct Flags: u32 {
        const RDONLY = 0;
        const WRONLY = 1;
    }
}

fn main() {
    println!("{:?}", Flags::RDONLY);
    println!("{:?}", Flags::from_bits_retain(0x100));
}
```
prints
```
Flags(0x0)
Flags(RDONLY | 0x100)
```
I don't have an opinion about whether it should print `RDONLY` in both or neither, but printing it in just one is confusing.

**Comment by KodrAus** [comment]
The value `0` isn’t recommended as a flag value because it behaves surprisingly with formatting, and with `is_any`.

**Comment by KodrAus** [comment]
If you do want to define a zero-valued flag I’d suggest defining the constant outside of the `bitflags!` macro.

**Comment by KodrAus** [comment]
Yeh, the logic it applies here when formatting is to print 0 as `0x0`, or for non-zero values, print each flag that can be unset from the input, then if there are any remaining bits set print that value as hex.

We could actually alter this somewhat to only print `0x0` if we didn’t print any other value. That way so long as your zero-valued flag appears first it’ll get printed.
