### ISSUE TITLE
Documenting bitflags: how to get documentation for the generated bitflags

### ISSUE THREAD

**Issue by leecbaker** [bitflags/bitflags#378]
Some code that I'm writing uses the `#![warn(missing_docs)]` macro to enforce a requirement that all public interfaces have documentation. I haven't been able to figure out how to generate documentation when using the `bitflags!` macro; I also haven't been able to turn off the linter warning using `#![allow(missing_docs)]`.

Is there a convenient way to add doc comments to a set of flags?
* If so, is there an example somewhere that I can reference? This would be a great thing to include in bitflags documentation.
* If not, then take this as a feature request!

**Comment by rusty-snake** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=530756068e54aa56eb519dd66c9fdfc5

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f782c74e49e8c4c4ae940125265eb7ed

**Comment by KodrAus** [comment]
Thanks @rusty-snake! Those would actually make some great compile-pass tests 🤔

**Comment by leecbaker** [comment]
Thank you @rusty-snake! I'm surprised I didn't figure this out myself!

What do you think about adding doc comments to the example in Readme.md?

**Comment by KodrAus** [comment]
@leecbaker Good idea :+1: I'll put those in
