### ISSUE TITLE
Feature guard `parser`?

### ISSUE THREAD

**Issue by GnomedDev** [bitflags/bitflags#382]
The parser module is most likely not used in a lot of projects, and simply contributing to compile time. I suggest a feature flag is added (and set in default_features to prevent breaking) around the whole parser module to save on some code size and compile times for a lot of the rust ecosystem.

**Comment by KodrAus** [comment]
Hi @GnomedDev! :wave:

The parser module is used by code generated by the `bitflags` macro for formatting/parsing so we can't make it conditional without also making the code it generates conditional.

**Comment by GnomedDev** [comment]
That still sounds useful

**Comment by KodrAus** [comment]
Making code generation features compile-time configurable is something I'd be interested in exploring, but at this stage not likely to pursue without any strong motivation for actual impact on compile times. It adds another layer of configuration complexity both for users to learn and for the project to maintain. We'd want to be sure it would actually be worth it.

**Comment by KodrAus** [comment]
It's been a while since there was any activity here. Since there's nothing immediately actionable here I'll go ahead and close this one to keep our issue list current, but would be open to revisiting if there's some concrete motivation with real-world impact.
