### ISSUE TITLE
Static member variable on the impl?

### ISSUE THREAD

**Issue by jestarray** [bitflags/bitflags#383]
```rs
bitflags! {
    #[derive(Default, Debug, PartialEq, Copy, Clone)]
    pub struct Something: u32 {
        const FOO = 0x1;
        const BAR = 0x2;
    }
}

impl Something {
    const FOOBAR: Something = Something::FOO | Something::BAR;
}

// cannot call non-const operator in constants
// calls in constants are limited to constant functions, tuple structs and tuple variants
// public.rs(355, 9): impl defined here, but it is not `const`
```
I could stick it into the struct def or write a function that just returns that constant but I'm wondering if there's a way I can just have it be a static member variable on the impl

**Comment by rusty-snake** [comment]
`const` != `static`

While the traits for operators are not const yet, the functions generated by bitflags! are. So you should be able to use `Something::FOO.intersects(Something::BAR)`.

It sounds a bit like your asking a XY question. What do you really want to solve?

**Comment by jestarray** [comment]
Oh, I can use `.union()` for this. And this is pretty much what i want to solve, so I'm closing, thanks!
