### ISSUE TITLE
[Feature Request] `repr(packed)` for internal bits types

### ISSUE THREAD

**Issue by GnomedDev** [bitflags/bitflags#384]
An option to use `repr(packed)` would be nice, at least for the private `InternalBitFlags` type generated by the derive in `struct` mode. This would reduce sizes for structs which include the type alongside other types as it reduces padding brought on by the alignment padding.

**Comment by KodrAus** [comment]
This is supported as of `2.4.2`.

**Comment by GnomedDev** [comment]
Is this? My PR allows for repr packed on `impl` mode, but not `struct` mode with derives.
