### ISSUE TITLE
[Feature Request] Smaller internal types with non-breaking size increases

### ISSUE THREAD

**Issue by GnomedDev** [bitflags/bitflags#385]
Currently in https://github.com/serenity-rs/serenity we have to use `u64` for all our flags types in case of the API we are wrapping making increases in the number of flags past the size we allotted. This could be fixed however inside bitflags, if the macro could generate a public API with the size provided but privately used the smallest integer type possible. This would have to be optional, for people using unknown bits, but would reduce memory size tremendously for my usecase.

A minimal, oversimplified example with made-up syntax of what I want is
```rs
bitflags! {
    struct Example: <u64> {
        const FLAG1 = 0b01;
        const FLAG2 = 0b02;
    }
}
```
to generate
 ```rs
struct Example(u8);

impl Example {
   pub fn bits(&self) -> u64 {
       self.0 as u64
   }
}
```

**Comment by rusty-snake** [comment]
from_bits_retain is part of the public API.

**Comment by KodrAus** [comment]
Thanks for the suggestion @GnomedDev. I don't think this is something we'll support so will go ahead and close this one. We're not considering making breaking changes to the API, and I'd like to avoid introducing features that interact poorly with any existing ones.

You could potentially support this through your own (might have to be a proc) macro that declares a type alias based on the largest input value. You can then use that generated type in the `bitflags!` macro.
