### ISSUE TITLE
[Feature Request] Serialize as struct of bools

### ISSUE THREAD

**Issue by randomairborne** [bitflags/bitflags#386]
Hello! I've been working on a project with templating where it would be useful to have access to a bitflags serialization as a map of booleans. Is this something that would be possible to support at all? Would a PR implementing it be accepted?

**Comment by KodrAus** [comment]
Hi @randomairborne :wave:

There are a few ways you could implement this. If you're using your own flags type with a known number of bits you may be able to use a custom bits type that is an array of booleans. We've actually got an example that demonstrates this here: https://github.com/bitflags/bitflags/blob/main/examples/custom_bits_type.rs

You can also do this generically using a function that iterates over bits, returning a boolean for each one that's set. You should then be able to write an adapter that serializes that iterator as a `serde` sequence. I've whipped up a quick demo of that here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3e5f9c92ac59d30792efeefd5b2ae96e

**Comment by randomairborne** [comment]
:O that's super cool! Thanks!
