### ISSUE TITLE
FR: Please make operators cosnt. bitwise or operator `|` is not const

### ISSUE THREAD

**Issue by ConnorBP** [bitflags/bitflags#399]
The bitwise operators overloads are not defined as const for some reason.

That results in this janky workaround being needed:

`FeatureSupport::from_bits_retain(FeatureSupport::WRITE_KEYBOARD.bits() | FeatureSupport::WRITE_MOUSE.bits()),`

when all that should need to happen is:

`FeatureSupport::WRITE_KEYBOARD.bits() | FeatureSupport::WRITE_MOUSE.bits(),`

**Comment by caelunshun** [comment]
Operator overloads can't be made `const` as Rust currently doesn't support `const fn` in traits.

**Comment by KodrAus** [comment]
Once we can make `|` and other bitwise operators `const` we definitely will :+1: In the meantime though the solution of using the generated set methods is the way to go.
