### ISSUE TITLE
Attribute or feature flag to remove flag name in the generated code

### ISSUE THREAD

**Issue by hehaoqian** [bitflags/bitflags#413]
The generated code of `bitflags` always contain the string of flag name,
make it much easier for reverse engineering,
and often such string is not needed.

For example, in bitflags 2.6.0

```
bitflags! {
    pub struct Flags: u32 {
        const A = 0b00000001;
        const B = 0b00000010;
        const C = 0b00000100;
    }
}
```

transfrom to

```
impl ::bitflags::Flags for Flags {
    const FLAGS: &'static [::bitflags::Flag<Flags>] = &[
        {
            #[allow(deprecated, non_upper_case_globals)]
            ::bitflags::Flag::new("A", Flags::A)
        },
        {
            #[allow(deprecated, non_upper_case_globals)]
            ::bitflags::Flag::new("B", Flags::B)
        },
        {
            #[allow(deprecated, non_upper_case_globals)]
            ::bitflags::Flag::new("C", Flags::C)
        },
    ];
    type Bits = u32;
    fn bits(&self) -> u32 {
        Flags::bits(self)
    }
    fn from_bits_retain(bits: u32) -> Flags {
        Flags::from_bits_retain(bits)
    }
}
```

---

Feature request:
One of the following:

1. Add a feature to `bitflags` crates to remove the literal string in the generated output
2. Add an attribute to `bitflags` macro to remove the literal string in the generated output

-----

Alternative solution:
Use verison of bitflags == "1.3.2", where the feature of flags <-> string do not exist

**Comment by rusty-snake** [comment]
1. Will break other dependencies in the same project.

**Comment by hehaoqian** [comment]
Add an attribute would be a compatible change

```
bitflags! {
   #[no_name]
    pub struct Flags: u32 {
        const A = 0b00000001;
        const B = 0b00000010;
        const C = 0b00000100;
    }
}
```

transform to 

```
impl ::bitflags::Flags for Flags {
    const FLAGS: &'static [::bitflags::Flag<Flags>] = &[
        {
            #[allow(deprecated, non_upper_case_globals)]
            ::bitflags::Flag::new("", Flags::A)
        },
        {
            #[allow(deprecated, non_upper_case_globals)]
            ::bitflags::Flag::new("", Flags::B)
        },
        {
            #[allow(deprecated, non_upper_case_globals)]
            ::bitflags::Flag::new("", Flags::C)
        },
    ];
    type Bits = u32;
    fn bits(&self) -> u32 {
        Flags::bits(self)
    }
    fn from_bits_retain(bits: u32) -> Flags {
        Flags::from_bits_retain(bits)
    }
}
```

**Comment by KodrAus** [comment]
Thanks for the suggestion @hehaoqian. The rationale here is a bit scant on detail and this feature also exists in `bitflags` `1.x` too; it's used in the generated `fmt::Debug` implementation.

We don't add any custom attributes to `bitflags` to control code generation to keep the scope of the project manageable so I don't think we'll be pursuing this, but if anyone else finds their way to this issue and wants to offer some more motivating use cases then we can certainly revisit it.
