### ISSUE TITLE
Feature request: Atomic bitflags

### ISSUE THREAD

**Issue by TadaHrd** [bitflags/bitflags#420]
I think bitflags could benefit if they had atomic versions.

**Comment by KodrAus** [comment]
Hi @TadaHrd :wave: We explored this previously in #391 and concluded that the additional complexity directly in `bitflags` is too much. It looks like there are alternatives like [`atomig`](https://docs.rs/atomig/latest/atomig/) can make this smoother for you though.

**Comment by TadaHrd** [comment]
> Hi @TadaHrd :wave: We explored this previously in #391 and concluded that the additional complexity directly in `bitflags` is too much. It looks like there are alternatives like [`atomig`](https://docs.rs/atomig/latest/atomig/) can make this smoother for you though.

Ah ok. If it's too complex, then it makes sense to avoid it.
